
data:
  myRows:
    path: "./testdata/data.csv"
    handler: csv
    properties: 
      - json
      - seq
      - 0
    #options
    #json || text
    #seq || rand
    #-1 = return every record on every request
    #0...n starting index (always reset to 0 when reach EOR)

  myPayload:
    path: "./testdata/test.json"
    handler: text

  folderData:
    path: "./testdata/"
    handler: folder

handler:
  "custom": 
    "myCustomHandler"

port: 8001

endpoints:
  "/orders":
    verb: get
    data: myPayload
    responseStatus: 200
    responseContentType: "application/json"
  
  "/folder":
    verb: get
    data: folderData

  "/api/folder":
    verb: get
    data: folderData
  
  "/people":
    verb: any
    responseStatus: 200

  "/user":
    verb: get
    data: myRows
    responseStatus: 200
    responseContentType: "application/json"

  "/custom":
    verb: get
    data: myPayload
    responseStatus: 200
    handler: custom
    responseContentType: "application/json"

log: verbose
  #debug
  #error
  #verbose
  #none